export const activity = [
  "Comercio al detal",
  "Alimentación / Gastronomía",
  "Tecnología / Telecomunicaciones",
  "Cuidado personal / Estética",
  "Salud",
  "Arquitectura / Construcción",
  "Comercio electrónico",
  "Educación",
  "Servicios especializados",
  "Servicios contables o financieros",
  "Consultoría",
  "Automotores y partes",
  "Agricultura / Ganadería",
  "Manufactura",
  "Artes / Manualidades",
  "Transporte / Logística",
  "Publicidad / Medios digitales",
  "Hotelería / Turismo",
  "Entretenimiento",
  "Organización sin ánimo de lucro",
  "Otros",
];
